### ISSUE TITLE
安卓启动单聊页面报错

### ISSUE THREAD

**Issue by xiaoyu915** [TencentCloud/TIMSDK#1229]
集成的含UI版本，看意思是找不到activity,项目里module注入了呀
android.content.ActivityNotFoundException: No Activity found to handle Intent { (has extr
    at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2120)
    at android.app.Instrumentation.execStartActivity(Instrumentation.java:1746)
    at android.app.Activity.startActivityForResult(Activity.java:5372)
    at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:
    at android.app.Activity.startActivityForResult(Activity.java:5308)
    at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:
    at android.app.Activity.startActivity(Activity.java:5755)
    at androidx.core.content.ContextCompat.startActivity(ContextCompat.java:251)
    at com.tencent.qcloud.tuicore.TUIRouter$Navigation.startActivity(TUIRouter.java:328)
    at com.tencent.qcloud.tuicore.TUIRouter$Navigation.navigate(TUIRouter.java:313)
    at com.tencent.qcloud.tuicore.TUICore.startActivity(TUICore.java:73)
    at com.tencent.qcloud.tuicore.TUICore.startActivity(TUICore.java:58)
    at com.tencent.qcloud.tuikit.tuichat.ui.page.TUIBaseChatActivity.startSplashActivity(
    at com.tencent.qcloud.tuikit.tuichat.ui.page.TUIBaseChatActivity.chat(TUIBaseChatActi
    at com.tencent.qcloud.tuikit.tuichat.ui.page.TUIBaseChatActivity.onCreate(TUIBaseChat
    at android.app.Activity.performCreate(Activity.java:8125)
    at android.app.Activity.performCreate(Activity.java:8113)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1320)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3888)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4098)
    at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:9
    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExec
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2475)
    at android.os.Handler.dispatchMessage(Handler.java:110)
    at android.os.Looper.loop(Looper.java:219)
    at android.app.ActivityThread.main(ActivityThread.java:8401)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1102)

**Comment by Tencent-Alice** [comment]
您好，根据您的问题，可以提供下相关报错截图和im sdk 吗，方便进一步定位问题
技术问题，欢迎交流，q2562367495

**Comment by yzjjdcf** [comment]
同
