### ISSUE TITLE
Android 模拟器登陆后报：java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by 120660021** [TencentCloud/TIMSDK#931]
模拟器型号：
Name: Pixel_API_30

CPU/ABI: Google Play Intel Atom (x86)

Target: google_apis_playstore [Google Play] (API level 30)
 
![1608626612893](https://user-images.githubusercontent.com/8433054/102868276-f4ddbe00-4474-11eb-9a64-601f2483cec6.jpg)

错误信息：
2020-12-22 16:34:39.837 13685-13685/com.tencent.qcloud.tim.tuikit E/loud.tim.tuiki: No implementation found for java.lang.String com.tencent.liteav.basic.util.TXCCommonUtil.nativeGetSDKVersion() (tried Java_com_tencent_liteav_basic_util_TXCCommonUtil_nativeGetSDKVersion and Java_com_tencent_liteav_basic_util_TXCCommonUtil_nativeGetSDKVersion__)
2020-12-22 16:34:39.839 13685-13685/com.tencent.qcloud.tim.tuikit E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.tencent.qcloud.tim.tuikit, PID: 13685
    java.lang.UnsatisfiedLinkError: No implementation found for java.lang.String com.tencent.liteav.basic.util.TXCCommonUtil.nativeGetSDKVersion() (tried Java_com_tencent_liteav_basic_util_TXCCommonUtil_nativeGetSDKVersion and Java_com_tencent_liteav_basic_util_TXCCommonUtil_nativeGetSDKVersion__)
        at com.tencent.liteav.basic.util.TXCCommonUtil.nativeGetSDKVersion(Native Method)
        at com.tencent.liteav.basic.util.TXCCommonUtil.getSDKVersion(TXCCommonUtil.java:39)
        at com.tencent.liteav.trtc.impl.TRTCCloudImpl.init(TRTCCloudImpl.java:459)
        at com.tencent.liteav.trtc.impl.TRTCCloudImpl.<init>(TRTCCloudImpl.java:352)
        at com.tencent.liteav.trtc.impl.TRTCCloudImpl.sharedInstance(TRTCCloudImpl.java:334)
        at com.tencent.trtc.TRTCCloud.sharedInstance(TRTCCloud.java:41)
        at com.tencent.liteav.model.TRTCAVCallImpl.<init>(TRTCAVCallImpl.java:396)
        at com.tencent.liteav.model.TRTCAVCallImpl.sharedInstance(TRTCAVCallImpl.java:375)
        at com.tencent.liteav.AVCallManager.initVideoCallData(AVCallManager.java:155)
        at com.tencent.liteav.AVCallManager.init(AVCallManager.java:144)
        at com.tencent.qcloud.tim.uikit.TUIKitImpl$1.onSuccess(TUIKitImpl.java:119)
        at com.tencent.imsdk.v2.V2TIMManagerImpl$1.onSuccess(V2TIMManagerImpl.java:169)
        at com.tencent.imsdk.common.ICallback$1.run(ICallback.java:24)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7523)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
    
    
    --------- beginning of system

**Comment by Tencent-Alice** [comment]
您好，根据提供的信息，您是在初始化音视频报错，是偶发还是常发问题？

**Comment by 120660021** [comment]
> 您好，根据提供的信息，您是在初始化音视频报错，是偶发还是常发问题？

必现，每次都会崩溃

**Comment by 120660021** [comment]
> 您好，根据提供的信息，您是在初始化音视频报错，是偶发还是常发问题？

这个是直接运行的demo，没有任何的代码改动

**Comment by Tencent-Alice** [comment]
OK，需要提供具体信息排查下。技术问题，欢迎私信，Q2562367495，注明来意

**Comment by zhangzuofa** [comment]
我也是 突然就这样为什么

**Comment by jidaojiuyou** [comment]
+1
一启动就会出现这个问题

**Comment by FlankT** [comment]
所以 解决了嘛 。

**Comment by Tencent-Alice** [comment]
您好， 这个报错一般是下载so文件不全导致的，可以现将缓存清空之后重新下载SDK之后重新gradle看下
如问题还会复现，欢迎交流 Q2562367495 注明来意

**Comment by FlankT** [comment]
我是远程依赖的api 'com.tencent.liteav:LiteAVSDK_TRTC:8.4.9947'
